import { LeafletElement } from './map/map';
import { LayerElement } from './layer/layer';
import { MarkerElement } from './marker/marker';
import { CircleElement } from './circle/circle';
import { PolygonElement } from './polygon/polygon';
import { PolylineElement } from './polyline/polyline';
import { LeafletGroup } from './group/group';
import { MapService } from './services/map.service';
import { GroupService } from './services/group.service';
export declare const CandTLeafletComponent: (typeof LeafletElement | typeof LeafletGroup | typeof CircleElement | typeof LayerElement | typeof MarkerElement | typeof PolygonElement | typeof PolylineElement)[];
export declare const CandTLeafletService: (typeof MapService | typeof GroupService)[];
